[package]
name = "rust-auth-service"
version = "0.1.0"
authors = ["Benjamin Faller", "Sebastian Voigt"]
edition = "2018"

[dependencies]
authorization = { path = "authorization" }
service-errors = { path = "service-errors" }

dotenv = "0.15.0"
actix-web = "3"

[workspace]
members = [
    "service-errors",
    "database-integration",
    "authorization"
]
