[package]
name = "authorization"
version = "0.1.0"
authors = ["Benjamin Faller", "Sebastian Voigt"]
edition = "2018"

[dependencies]
futures = "0.3.14"
actix-service = "1"
actix-web = "3"

access-control = { path = "../access-control" }
